---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install common packages
  apt:
    name: 
      - curl
      - vim
      - htop
    state: present
  become: yes

- name: Set timezone
  timezone:
    name: UTC
  become: yes