---
- hosts: all
  tasks:
    - name: Update common configurations
      template:
        src: common_config.j2
        dest: /etc/common_config.conf
      become: yes

- hosts: web
  tasks:
    - name: Update Nginx configuration
      template:
        src: nginx_config.j2
        dest: /etc/nginx/sites-available/default
      become: yes
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: yes